version: '1.0'
services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: dbuser
        POSTGRES_PASSWORD: cleanArchitecture
        POSTGRES_DB: clean_architeture_database
      ports:
        - "5432:5432"
      volumes:
        - postgres-storage:/var/lib/postgresql/data

volumes:
  postgres-storage: